# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 325db4a3c86d0014f62b7eec4603f491c8474cdaf24ba871beee74d367006728c7b3e979e8522e263bd98ef97532b94c225fad7feaa3e8bfbcf10c99e033ff54

test:
  secret_key_base: 4bf22de69fdb5ab401883a4c87a7535b625cac39301c0c0cf03249d0ea184250ca675a814e22f5bbe3ade720ec3447eaff8db006170c51c103f07b1a97d1ce8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
